live_config_reload = true

# Windows only
# [shell]
# program = "C:\\Windows\\System32\\wsl.exe ~"
# args = ["-d Ubuntu-24.04"]

[window]
opacity = 0.8
padding.x = 16
padding.y = 16
decorations = "buttonless"

[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"
size = 14.0

[colors.primary]
background = '#000000'
foreground = '#ffffff'

[colors.cursor]
text = '#F81CE5'
cursor = '#ffffff'

[colors.normal]
black   = '#000000'
red     = '#fe0100'
green   = '#33ff00'
yellow  = '#feff00'
blue    = '#0066ff'
magenta = '#cc00ff'
cyan    = '#00ffff'
white   = '#d0d0d0'

[colors.bright]
black   = '#808080'
red     = '#fe0100'
green   = '#33ff00'
yellow  = '#feff00'
blue    = '#0066ff'
magenta = '#cc00ff'
cyan    = '#00ffff'
white   = '#FFFFFF'